### PR TITLE
Design layout

### PR DESCRIPTION
**Pull request by camargozzini**

### CODE REVIEW

**Comment by bertocq** [comment]
Hey @camargozzini I think you were trying to open a pull request to your fork... But somehow ended up opening one against consul itself 🤔 am I right? 😃

**Comment by camargozzini** [comment]
Yes! @bertocq , i'm sorry!

**Comment by bertocq** [comment]
No problem @camargozzini ^_^ But you broke our ❤️ 's 😄  we though we were going to get some cool contributions from Chile!! Feel free to join https://gitter.im/consul/consul and we can give you some advice to keep your consul fork updated (it's two releases behind) 👍  and also about what changes you needed and if it could be nice to port them back to consul itself :)

**Comment by camargozzini** [comment]
I will! thank you @bertocq !

**Pull request closed without merging**
