### PR TITLE
Fix the missing link for Technical Assistance in footer

### PR DESCRIPTION
**Pull request by chkoun**
## References

https://github.com/consul/consul/issues/722

## Objectives
Right now there is a 'Technical Assistance' link in the footer, but without links

> What are the objectives of these changes?
There is already a section Technical problems? unser the Help page
Screenshot from 2021-11-06 13-18-31

We can fix the missing link in the footer by linking to the Help Page when the Help Page feature is enable

## Visual Changes
Currently 
Screenshot from 2021-11-06 13-15-13

After changes if Help feature is enabled 
Screenshot from 2021-11-06 13-14-43

After changes if Help feature is disabled 
Screenshot from 2021-11-06 13-17-20

## Notes

We string layouts.footer.contact_us will not be displayed when the help page is not enable but currently it does not make sense to display it without link

### CODE REVIEW

**Comment by javierm** [comment]
@chkoun Thanks for this pull request! :pray:

Would it be possible to add a test which fails without the changes in this pull request and passes thanks to them? That way we make sure we don't accidentally introduced the bug.

Also related to #3125.

**Comment by chkoun** [comment]
@javierm This is my very first PR and I am still learning about programming and github :smile: 
I went over the Github worflows test file but this task seems a bit out of my reach for now. However I will be glad to learn by checking how it will be done for next time. Sorry for not being able to help

**Comment by javierm** [comment]
@chkoun No problem :ok_hand:. Thank you very much for your contribution :smile:.

We'll have a look at this pull requests and check whether we can write tests for it. Right now we're preparing version 1.4.0 and are in the middle of the testing phase, so it might take a while. Thank you for your patience!

**Comment by javierm** [comment]
@chkoun Since we're still deciding how to handle the Help/FAQ/Docs links, and since with the current format handling translations in certain languages would be quite hard, how about removing the broken text while we make a decision? Here's a suggested patch:

```diff
diff --git a/app/views/layouts/_footer.html.erb b/app/views/layouts/_footer.html.erb
index f1ad2f47e..8b63dbab5 100644
--- a/app/views/layouts/_footer.html.erb
+++ b/app/views/layouts/_footer.html.erb
@@ -9,10 +9,6 @@
         <%= sanitize(t("layouts.footer.description",
           open_source: link_to(t("layouts.footer.open_source"), t("layouts.footer.open_source_url"), target: "blank", rel: "nofollow"),
           consul:  link_to(t("layouts.footer.consul"), t("layouts.footer.consul_url"), target: "blank", rel: "nofollow"))) %>
-        <% if feature?(:help_page) %>
-          <%= t("layouts.footer.contact_us") %>
-          <%= link_to t("layouts.header.help"), help_path %>
-        <% end %>
       </p>
     </div>
 
diff --git a/config/locales/en/general.yml b/config/locales/en/general.yml
index 3857076a8..f36edf408 100644
--- a/config/locales/en/general.yml
+++ b/config/locales/en/general.yml
@@ -213,7 +213,6 @@ en:
       conditions: Terms and conditions of use
       consul: CONSUL application
       consul_url: https://github.com/consul/consul
-      contact_us: For technical assistance visit
       copyright: CONSUL, %{year}
       description: This portal uses the %{consul} which is %{open_source}.
       open_source: open-source software
diff --git a/config/locales/es/general.yml b/config/locales/es/general.yml
index 16cd81b01..34f132ada 100644
--- a/config/locales/es/general.yml
+++ b/config/locales/es/general.yml
@@ -213,7 +213,6 @@ es:
       conditions: Condiciones de uso
       consul: aplicación CONSUL
       consul_url: https://github.com/consul/consul
-      contact_us: Para asistencia técnica entra en
       copyright: CONSUL, %{year}
       description: Este portal usa la %{consul} que es %{open_source}.
       open_source: software de código abierto
```

**Comment by chkoun** [comment]
@javierm Yes sure that works too. Better to have no sentence than an incomplete one.
I will close this PR as this can be included in #4737

**Comment by javierm** [comment]
@chkoun :ok_hand: Then we'll continue in pull request #4752.

**Pull request closed without merging**
