### PR TITLE
Parameterize brand and social links

### PR DESCRIPTION
**Pull request by josepjaume**
This is an effort to remove references to any particular city or location from consul's codebase and add everything that I can as a setting.

This PR tackles:

- [x] Brand's name.
- [x] Social links

### CODE REVIEW

**Comment by kikito** [comment]
Hi, happy new year, thanks a lot for your PR!

I finally had time to review it and I have some comments:

* Could you remove the `setting` helper? I don't think it adds much to the scenario and it makes things confusing by offering two very similar ways of doing the same thing (as an example, in your own pull request there are some views using `Setting[...]` and other using `setting(...)`).
* Could you rename `brand_name` to `org_name`? Consul might be installed in places which are not a brand (Madrid isn't, for instance).
* ¿Can you fix the git merge conflicts, too?

Thanks again!

**Comment by josepjaume** [comment]
Hi @kikito, of course! Everything you said makes a lot of sense. Will get to it when I get some time! :+1:

**Comment by josepjaume** [comment]
@kikito I've applied your changes and rebased to latest master :)

After this, I'd like to work on feature flags. I've been thinking a bit about how to implement that, and although `rollout` does its job, I think we could manage to do the same with `Settings` (but we'd loose the A/B testing facilities which I don't think we need anyway).

That said, I don't feel comfortable in hitting the database every time we check for a setting. Redis might do a better job here, right?

So my proposal would be:

* Use redis for storing all the settings
* Move feature flagging to settings under a `feature.X` namespace (`Settings['feature.debates']`).
* Use feature flags to hide views and within `cancan` to disable entire features.

What do you think?

**Comment by xuanxu** [comment]
:+1: 
One last detail: adding comments to the code in setting.rb ( https://github.com/consul/consul/pull/763/files#diff-8c3f2a547e7f7d66e1756971a1ef20c2R7 ) brakes the norm we are using, could you delete them?

**Comment by josepjaume** [comment]
Of course! Is that written somewhere so I can adhere to it in further PRs?

**Comment by josepjaume** [comment]
Done!

**Comment by xuanxu** [comment]
Thanks!
The general styleguide and best practices policy is just linked in the Contributing.md file but I don't think it mentions explicitly anything about comments. In this case is just about following the format of the existing code. Right now there's no comments in methods, so adding comments only to some of them would make the repo inconsistent.

**Pull request merged**
