### PR TITLE
20170912 - Disabled user questions for polls into budgets view.

### PR DESCRIPTION
**Pull request by zamuro**
Issue #1836

### CODE REVIEW

**Comment by bertocq** [comment]
Conflicts appear because wairbut-m2c/consul fork isn't up to date with latest consul/consul changes. That should be done on a regular basis to avoid this issues. Check https://consul_docs.gitbooks.io/docs/content/es/forks/update.html for guided steps.

**Comment by zamuro** [comment]
Please confirm if this is the desired behavior.

captura de pantalla_2017-09-15_10-41-22

**Comment by bertocq** [comment]
@zamuro about the behaviour yes, now it's not expanding the Votaciones menu and not marking as active the Preguntas ciudadanas submenu.

About implementation, have you read my previous comment about the condition used to check if something should be active?

Also I think you're still not using editorconfig correctly on your IDE/Text editor

screen shot 2017-09-15 at 10 48 12

That extra green means you've added some amount of trailing blank spaces somehow

**Comment by zamuro** [comment]
I have read the change in the controller you suggested. Nevertheless, It is not working as expected after I tried implementing it. That's why I haven't made the changes as required. I will fix the spacing and rebase the current commit.

**Comment by bertocq** [comment]
@zamuro maybe I explained myself wrongly about the code changes, [here is my solution](https://github.com/consul/consul/compare/1836%23fix_questions_admin_menu?expand=1), feel free to git checkout that branch `1836#fix_questions_admin_menu` and test locally the expected behaviour

**Pull request merged**
