### PR TITLE
Extract mailer from name and address to a setting

### PR DESCRIPTION
**Pull request by ferblape**
This PR proposes to extract to a setting the mailer from name and email address. This would be really helpful to parameterize a new Consul fork.

BTW, it also takes care of #1146 

Please, review and provide feedback.

### CODE REVIEW

**Comment by ferblape** [comment]
Hmmm, there's a problem using a Setting in an initializer when running the tests, because the table doesn't exist (it fales in the `rake db:setup` task).

I suggest something like:

```
# config/initializers/devise.rb

  if Rails.env.test?
    config.mailer_sender = "noreply@example.org"
  else
    config.mailer_sender = "#{Setting['mailer_from_name']} <#{Setting['mailer_from_address']}>"
  end

```

**Comment by xuanxu** [comment]
:+1: Thanks Blat!
Can you add that change to the devise.rb initializer? 
(and now that you are at it, it would be better if the default emails in seed files are @consul.dev instead of consul.es)

**Comment by ferblape** [comment]
Of course!

**Comment by ferblape** [comment]
This is green in my travis! https://travis-ci.org/ferblape/consul

**Comment by xuanxu** [comment]
Yay!

**Pull request merged**
