### PR TITLE
Switch flag/unflag buttons on use via ajax

### PR DESCRIPTION
**Pull request by xarlybovi**
Where
=====
* **Related Issue:** #1797

What
====
- Refresh proposal flag/unflag button via AJAX

How
===
- Implemented like follow/unfollow button and reloaded foundation in order to fix dropdown on AJAX partial render

### CODE REVIEW

**Comment by voodoorai2000** [comment]
This is great @xarlybovi!

A small detail, the flaggable concern is used by another two models, `debates` and `comments`.

Could you use `resource_id` instead of `proposal_id` and add a couple of specs to make sure these changes fix the problem?

**Comment by xarlybovi** [comment]
Yeah, sure!

**Comment by xarlybovi** [comment]
@voodoorai2000 Done.

**Comment by voodoorai2000** [comment]
Great! Appreciate it @xarlybovi

**Pull request merged**
