### PR TITLE
Share with WhatsApp

### PR DESCRIPTION
**Pull request by Ana06**
Issue #941

I have added the gem _font-awesome-sass_ to use the Whatsapp icon. I suppose that we only want to show it in mobiles. I have added the Whastapp icon in debates and proposals, is there any other place where I should add it?

I think It look nice like that:

screenshot_2016-03-11-00-26-12

I have put the debate/proposal tittle and the link in the text for Whatsapp, so it looks like that:

screenshot_2016-03-11-00-00-24

Maybe we want to change the text.

### CODE REVIEW

**Comment by xuanxu** [comment]
@Ana06 un pequeño consejo: cuando hagas cambios para enviar una PR lo mejor es crearte una rama específica para ello en tu repo, no hacerlo en master. Así te ahorrarás conflictos cuando hagas pull del repo original. La idea es mantener ambas master sincronizadas y usar ramas para los cambios.

**Comment by decabeza** [comment]
Hi @Ana06,

Thanks you very much! Only a few comments:

- For CSS classes use hyphen instead of underscore (.social-share-full instead of .social_share_full) :wink:

- For icons we use a font (generated in http://fontastic.me/) you can remove the gem font-awesome-sass (it´s not neccesary), and replace the icon font files for these:

[fonts.zip](https://github.com/consul/consul/files/169150/fonts.zip)

- Also include this on **`/stylesheets/icons.scss`**:

<code>
**.icon-whatsapp:before {
  content: "\50";**
} 
</code>

And you can use **`<i class="icon-whatsapp"></i>`** for the icon.

**Comment by Ana06** [comment]
@xuanxu gracias por el consejo, lo haré así a partir de ahora :wink:

I hadn't noticed that you where using fontastic, I have changed it. :smiley:

**Comment by decabeza** [comment]
:tada:

**Pull request merged**
