### PR TITLE
Fix for `voting comments` flaky specs

### PR DESCRIPTION
**Pull request by aitbw**
Where
=====
* **Related PR:** AyuntamientoMadrid/consul#1212

What
====
* Backport the aforementioned PR into CONSUL to avoid possible flaky specs, see original PR for more details

Test
====
* Fixed coverage, all green! ✅

### CODE REVIEW

**Comment by bertocq** [comment]
We've a possible reactivation of the Budget::Investment flaky (https://github.com/AyuntamientoMadrid/consul/issues/1192), lets put on hold this backport for now

**Comment by aitbw** [comment]
Apparently, the reactivation of the `comments/budget_investments#update` scenario was related to a custom Decide Madrid spec that was fixed on AyuntamientoMadrid/consul#1241

Commit [`dc45743`](https://github.com/AyuntamientoMadrid/consul/commit/dc4574380fdb164ef57f5fb7d16615eea5759565) from the aforementioned PR was cherry picked to this pull request to ensure maximum consistency on both codebases and to avoid possible flakys

**Comment by aitbw** [comment]
The latest Travis CI build for this PR raised a flaky that was supposed to be fixed on [`f7dd9d7`](https://github.com/consul/consul/pull/2448/commits/f7dd9d7089493f8bd7ef6ab5803445673b77a050) —I'll have a look at this as soon as possible

**Comment by aitbw** [comment]
Closed in favor of #2534

**Comment by javierv** [comment]
I can confirm all six flakies are still present and fail once in a while on my machine.

I think they fail for the same reason #2713 fails: clicking a link while it's being replaced by a new one. As explained in #2734, I see two possible solutions in this scenario: one of them would be merging this pull request (although the logout part is probably not necessary), since it changes the tests so they check the page between clicks, and the other one would be not to regenerate the "in favor" and "against" links, like it's done in #2734.

@aitbw Let me know which solution you think is better (maybe #2734 would be the better place to continue this conversation), and maybe we can use the same solution in both pull requests :v:.

**Pull request closed without merging**
