### PR TITLE
Implement feature to allow multiple answers to be given for questions…

### PR DESCRIPTION
**Pull request by datamints-off**
… in polls.

For a customer of us we implemented a new feature for polls: you can set for individual questions the option to ggive multiple answers for that question. The UI allows for taking back given answers for such questions, the stats are showing the data correctly.

### CODE REVIEW

**Comment by javierm** [comment]
@datamints-off Thank you very much for the pull request! :pray:

We need to check the situation regarding poll answers :thinking:. We used to have support for this and other votation types, but it was removed in pull request #3806 because it had several bugs and security issues.

Right now we're starting our summer "holidays" (we'll still be around, but not as much as we usually do), and the we'll prepare version 1.4.0. In the meantime, if you'd like us to consider this pull request, would you mind adding tests for this feature?

**Comment by javierm** [comment]
@datamints-off After some discussion, we've decided this pull request is a great way to start introducing new votation types. Could you add some tests to it? Then we can start reviewing it.

Thanks! :wink:

**Comment by datamints-off** [comment]
@javierm Yes I can add some tests for that, but only after my holidays, probably in the first week of September.

**Comment by javierm** [comment]
@datamints-off Cool, thanks! Enjoy your holidays! :beach_umbrella:

**Comment by datamints-off** [comment]
I'm sorry that I have to close this pull request, but our customer stopped the project at this stage and so we have no funding for the automated tests. Maybe the client's new contractor will finish this.

**Comment by javierm** [comment]
That's a shame! Thank you for contributing anyway :pray:.

**Pull request closed without merging**
