### PR TITLE
Call load_categories when failed to save investment

### PR DESCRIPTION
**Pull request by 16yuki0702**
References
===================
- Addresses issue: https://github.com/consul/consul/issues/2855 - 500 error when we created a budget investment from management panel

Objectives
===================
- Fixed NoMethodError.
It occurs When it fails to @investment.save in create.
because it attempt to render new page without categories variable.
So I added a load_caregories method when it failed.

- I Fixed storing map location error.
Error occurs when storing map location, or skipping map.
I fixed it so that you can store map location, or skip map location.

### CODE REVIEW

**Comment by sturpin** [comment]
Good job @16yuki0702 !! :+1:

**Comment by sturpin** [comment]
Hi @16yuki0702 , I found a small detail... I tell you in case you think it's not very complicated to solved.
I've verified that if you uncheck the privacy policy, allows you to create the investment equally.
For me there is no problem as it's an internal panel....

**Comment by 16yuki0702** [comment]
@sturpin Thanks, I'll check it.

**Comment by 16yuki0702** [comment]
I investigated why it passed validation when if you uncheck the privacy policy,
I found that terms_of_service is assigned with "1" in controller.

It is not only
```
app/controllers/management/budgets/investments_controller.rb
```
but also
```
app/controllers/management/users_controller.rb
```

It seems to attempt to pass the validation whether terms_of_service is checked or not.
I don't know why it does, so would anyone teach me about this ??

If the policy of modification it is settled,
I want to fix it in another PR, OK??
(Because I think it is out of range in this PR)

**Comment by sturpin** [comment]
Yes @16yuki0702 I agree with you, keep me informed :)

**Comment by javierm** [comment]
@16yuki0702 Thank you very much for your contribution :heart:!

Since you're working on the issue, would it be possible to add a test so we catch this bug immediately if we reintroduce it in the future?

Thanks a lot!

**Pull request closed without merging**
