### PR TITLE
Update ruby version docker

### LINKED ISSUE #3991: Docker image unable to build
### User Story

As a developer, I want to run consul in container so I followed the guide to run consul in local

### Why is this Needed?

Docker image is not built due to an error with gems

### Description

*Type*: BUG

### Current Behavior
 `docker build` thrown an error:
```
user_agent_parser-2.6.0 requires ruby version >= 2.4, which is incompatible with
the current version, ruby 2.3.8p459
The command '/bin/sh -c bundle install --full-index' returned a non-zero code: 5
```

### Expected Behavior
to build the docker image without error

### Steps to reproduce
just trying to build the docker image as describedin the guide: https://docs.consulproject.org/docs/english-documentation/introduction/servers/docker

Downloaded the latest master version: d3fa00b1e60bc391d15306a3e5109b520fa13deb (HEAD -> master, origin/master, origin/HEAD)

See full output here https://gist.github.com/RuBiCK/c0cbaa674a6311aeb9546b921e513bf2

### PR DESCRIPTION
**Pull request by luchiago**
## References

* Closes #3991

## Objectives

The objective is updating the ruby version on Dockerfile due to one error that was appearing on build

## Screenshots

docker-problem

### CODE REVIEW

**Comment by javierm** [comment]
@luchiago Thanks for this pull request! :smile:

Just a question: are all these changes needed for the upgrade? It seems to me only the first commit is related to upgrading Ruby :thinking:, but I might be wrong :wink:.

**Comment by luchiago** [comment]
> @luchiago Thanks for this pull request! 
> 
> Just a question: are all these changes needed for the upgrade? It seems to me only the first commit is related to upgrading Ruby , but I might be wrong .

@javierm The other commits are optimization that I made, but if you feel they aren't necessary I can remove them.

**Comment by javierm** [comment]
It would be better to remove them since right now nobody on the team uses Docker and so it's hard to review them :relieved:.

Feel free to open a new pull request with those changes, although for the reason I've mentioned I can't give an estimate on when we'll be able to merge them.

Thanks for understanding! :pray:.

**Comment by luchiago** [comment]
@javierm Alright. I'll send another PR with those changes and why I'm making them. I left only the upgrade on ruby version.

**Pull request merged**
