### PR TITLE
Change log level in production to warn

### PR DESCRIPTION
**Pull request by artofhuman**

### CODE REVIEW

**Comment by bertocq** [comment]
Hello @artofhuman , as I said on your other PR, Raimond is on holiday leave :) so no answer from him for a while. And in this particular PR, I think you're totally right, but as my experience on the codebase is not longer than some months, I would rather wait for Raimond to comeback and share any knowledge that might be behind that production debug logging level before merging this PR.... just in case :). Is that ok for you? 

Thanks again for your contributions 👍 😃

**Comment by artofhuman** [comment]
> Is that ok for you?

Yes ;)

**Comment by voodoorai2000** [comment]
Yes, this is great @artofhuman, appreciate it!

**Pull request merged**
