### PR TITLE
Legislation processes documents

### PR DESCRIPTION
**Pull request by ortegacmanuel**
Where
=====
* **Related Issue:** #2041

What
====
- Adds documentable feature to legislation processes

How
===
- Adding documentable concern to Process model
- Adding a new partial _additional_documents to documents views
- Adding a new test to ensure document is shown in process show

Screenshots
===========

screenshot-2017-10-19 con documentable

### CODE REVIEW

**Comment by ortegacmanuel** [comment]
@decabeza @bertocq and everyone! here I send you a first version of adding legislation processes documents. 

I have mainly two doubts:

**Humanized method**: I created a new method in order to show the file type in a humanized way. I'm not sure where I should put it, firstly I did put it in the `DocumentsHelper` but finally I decided to add it as instance method to the Document model. where do you find I should put it?

**Test**: I added a new test scenario in `legislation/processes_spec.rb` to ensure that the document is shown in process show.

And in general, tell me if something is not properly implemented or something is missing. wiling to fix it or add it. Thanks!

**Comment by voodoorai2000** [comment]
Thank you so much @ortegacmanuel!
This is fabulous 😌 

The humanize method in the model looks great and the test too :)

**Comment by voodoorai2000** [comment]
Hey @ortegacmanuel 
It be great to also test the uploading of documents from the admin interface.
We’ve created a separate [issue](https://github.com/consul/consul/issues/2119) for this, feel free to tackle if you wish 😌

**Comment by ortegacmanuel** [comment]
@voodoorai2000 Great! I take it! :)

**Comment by voodoorai2000** [comment]
Awesome @ortegacmanuel! 😍

**Pull request merged**
