### PR TITLE
Annotator

### PR DESCRIPTION
**Pull request by voodoorai2000**
Creates Legislation concept.
Uses annotations for Legislations instead of Proposals.
Adds annotation specs.

### CODE REVIEW

**Comment by xuanxu** [comment]
:tada:

**Comment by voodoorai2000** [comment]
Thanks @abisosa @rodowi!

That’s fucking teeeeeamwooooooork!

**Comment by rodowi** [comment]
awesome :fireworks:

**Comment by abisosa** [comment]
Great ! :+1:

**Pull request merged**
