### PR TITLE
Upgrade gem coffee-rails to version 4.2.2

### PR DESCRIPTION
**Pull request by PierreMesure**
References
===================
- #2829

Objectives
===================
- Support digest resolution for coffee templates.
- See change log from 4.2.1 [here](https://github.com/rails/coffee-rails/blob/master/CHANGELOG.md)

Visual Changes
===================
- No visual changes

Notes
===================
- Nothing to do to update

### CODE REVIEW

**Comment by PierreMesure** [comment]
I've been trying to update a few gems tonight. I opened pull requests to [my own fork](https://github.com/PierreMesure/consul/pulls) to check if the CI was passing without bloating the list of the main repo. Turns out one test is failing, but it also fails on master so we can assume that they pass?

I'd like to use this pull request as an example as I haven't seen anyone open any related to #2829 yet. @voodoorai2000 or others, please give as much feedback as you can so the next gem update PRs can be of better quality. If this one passes, I'll transfer the others and try to update some more gems.

**Comment by aitbw** [comment]
**Note to reviewers**: this PR should only be merged if #2631 isn't merged first, as said PR also includes this change

**Comment by voodoorai2000** [comment]
Hey @PierreMesure!

Right, that is indeed a flaky/unrelated spec that should be fixed real soon 😌
Feel free to send these PRs to CONSUL's repo 👍

**Comment by voodoorai2000** [comment]
Hodoooor https://github.com/consul/consul/issues/2829#issuecomment-418827239

**Comment by voodoorai2000** [comment]
Hey @PierreMesure, 

That flacky has been solved 🎉 

We'll get this PR in, however @greysteil Dependabot seems to be working very nicely[1], we'll probably switch from manual gem upgrades to his app 😌

[1] https://github.com/consul/consul/pull/2877

**Pull request merged**
