### PR TITLE
Fix bug flagging legislation proposals

### PR DESCRIPTION
**Pull request by volcov**
## References

fix: #3554

## Objectives

The problem was in "scope", the routes and render did not point to legislation. 
Was trying to flag a proposal and not a legislation proposal

### CODE REVIEW

**Comment by volcov** [comment]
I looked travis, but I think what broke is some inconsistency of the CI itself =/

Captura de tela de 2019-10-11 09-13-31

**Comment by javierm** [comment]
> I looked travis, but I think what broke is some inconsistency of the CI itself

Could be; that build certainly took an unusually long time :thinking:. Could you execute `git commit --amend` and `git push -f` to force a new Travis build? :pray: That way we'll make sure it was Travis' fault.

By the way, thanks a lot for this pull request! :smile: I'll have a look at it next week.

**Comment by javierm** [comment]
One quick thing, though: could you add a test which fails without the changes in this pull request, but passes thanks to the fix in this pull request? That way we'll know if the bug shows up again :wink:.

**Comment by volcov** [comment]
> One quick thing, though: could you add a test which fails without the changes in this pull request, but passes thanks to the fix in this pull request? That way we'll know if the bug shows up again

good idea, i will do that :smiley:

**Comment by javierm** [comment]
Hi @volcov! :smile: Are yu still working on this pull request? :thinking:

**Comment by volcov** [comment]
> Hi @volcov! smile Are you still working on this pull request? thinking

OH MAN! Sorry =/

I was traveling to WebSummit, and now that I'm back, I changed company hahaha. 
so I was a little confused, I'm going back to work on it in the coming weeks =)

**Comment by javierm** [comment]
Hi @volcov! :smile: Are you still working on this pull request?

Since we'd like to include this fix in version 1.1, if you aren't available I can open a new pull request with your commits and then add another commit with the test.

**Comment by javierm** [comment]
Closing since the original author doesn't seem to be working on this pull request.

@volcov Thank you for your contribution! :smile: I've opened pull request #3948 using your commits, and will continue its development from there.

**Pull request closed without merging**
