### PR TITLE
Update documents.yml - add new Russian translation

### PR DESCRIPTION
**Pull request by LumaRay**

### CODE REVIEW

**Comment by decabeza** [comment]
@LumaRay thank you very much for all Russian translations! 😍

We merge all PR's: #3205, #3204, #3206, #3207, #3208, #3209, #3210, #3211, #3212, #3213, #3214, #3215, #3216, #3217, #3218, #3219, #3220, #3221, #3222, #3223, #3224, #3226, #3225.

For the future, better than PR's, we use [Crowdin](https://crowdin.com/project/consul) to manage translations. You can see more information on [Texts & Translations CONSUL documentation](https://consul_docs.gitbooks.io/docs/content/en/customization/translations.html).

Feel free to signup on Crowdin and contact us, we will be happy to include you as a translator. 🙏 😌

**Comment by LumaRay** [comment]
Hi @decabeza! Thank you for the invitation, I didn't know about that dedicated portal, Crowdin. 
Actually I'm quite new to GitHub, but I loved the Consul application - it's the best and actively maintained!
I have just registered with Crowdin https://crowdin.com/profile/LumaRay
Best of luck!

**Comment by LumaRay** [comment]
Hi, @decabeza, I have received an email from Crowdin asking to translate few lines, but as I logged in there few minutes ago, I saw that there were very few Russian translations at all: https://www.screencast.com/t/MaCIrotDwj
Maybe I did something wrong and opened the wrong link? Sorry, I'm quite new to that Crowdin portal...

**Comment by decabeza** [comment]
Hi @LumaRay,

Now we have to sync `master` branch with Crowdin. We are polish this part trying to automatise this action the most possible.

I contact to you when Crowdin be updated. 🙏 😌

**Comment by decabeza** [comment]
Hi again @LumaRay,

We sync Crowdin with CONSUL and it seems [Russian translations](https://crowdin.com/project/consul/ru#) already appear on Crowdin. 👏 🇷🇺

**Pull request merged**
