### PR TITLE
API docs and sample Ruby scripts

### PR DESCRIPTION
**Pull request by amiedes**
Where
=====
* **Related Issue:** #1754 

What
====

Adds API docs and a couple of Ruby scripts to show how to query the API using a HTTP library.

Hope you find this useful! 😅 

PD: I wasn't sure about where to locate this docs within the `doc` directory. Feel free to relocate this wherever you want.

### CODE REVIEW

**Comment by bertocq** [comment]
Really awesome @amiedes If you don't plan doing an English translation, I'll do it gladly :).

Also I would add references from the api markdown file to both ruby example files just to help make it easier to find.

**Comment by amiedes** [comment]
I'll work on that @bertocq! 👍

**Comment by amiedes** [comment]
Done ✅

**Comment by voodoorai2000** [comment]
Beautiful, thank you @amiedes! 👏 🎉

**Pull request merged**
