### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by cldha**
This pull request contains the locales files for the French language.

### CODE REVIEW

**Comment by voodoorai2000** [comment]
Hello @cldha !

Thank you very much, this is awesome!

There seems to be some failing specs though, looks like a syntax error in verification.fr.yml.

Can you have a look at it please?

**Comment by decabeza** [comment]
Hi @cldha!

Is a small change on `verification.fr.yml:56`

`document_number_help_text_html: '<strong>Carte d'identité</strong>: 12345678A<br> <strong>Passeport</strong>: AAA000001<br> <strong>Carte de résident</strong>: X1234567P'`

You must change to double quotes 😉

`document_number_help_text_html: "<strong>Carte d'identité</strong>: 12345678A<br> <strong>Passeport</strong>: AAA000001<br> <strong>Carte de résident</strong>: X1234567P"`

**Comment by cldha** [comment]
Hi @voodoorai2000, @decabeza, 

Thank you for the feedback and sorry for the delay. I've corrected the verification.fr.yml file. I will check the Travis build once it's completed to make sure everything is ok. 

Kind regards,
Claire

**Comment by voodoorai2000** [comment]
Hey @cldha !

Thank you very much!

We have an open [issue](https://github.com/consul/consul/issues/1531) regarding a translation service.

Please give us a little more time to try out the options and make sure this is the definite file structure for translations, before accepting your PR :)

**Comment by voodoorai2000** [comment]
Thank you @cldha!!!

**Comment by bertocq** [comment]
Hi @cldha!

At CONSUL we’re going to send a gift to each of our github contributors, and would love to send you one 😊.

I couldn't find any other way to contact you (the email on your commit messages `claire.dhaene@smile.fr` doesn't work anymore 😞 so I just realized github mention could do the trick 🤔 

 Can you share with us an address for the shipment with a private message or email? I'm @bertocq at Twitter/Gmail/Telegram/etc.. whatever suits you best :) 

Thank you again for being a contributor, you’re awesome 🤗!

**Pull request merged**
