### PR TITLE
Allow create legislation proposals on process draft phase

### LINKED ISSUE #3180: Allow create legislation proposals on process draft phase
### Background

Admin users can create processes on `/admin/legislation/processes/new`. Sometimes admins want to create some initial content before starts.

### References

Related previous issue: **Legislation process draft phase** https://github.com/consul/consul/issues/2930

### What we need

Allow create legislation proposals on `legislation/processes/N/proposals` if process draft phase is enabled (although the rest of phases are disabled).

### Screenshots
draft_phase

proposals

### PR DESCRIPTION
**Pull request by jaflutz**
## References

Closes #3180 - Allow create legislation proposals on process draft phase

## Objectives

Display the button 'Create a proposal' when the process is in draft phase

### CODE REVIEW

**Comment by javierm** [comment]
@jaflutz Fixed by #3534 :smile:.

**Comment by jaflutz** [comment]
Hi!
I think the error from travis-ci is not related to the changes in these PR, anyone can fire up travis again?
Thanks!

**Comment by jaflutz** [comment]
Hi @javierm! Thanks for the review, so sorry for the mistakes!! I'll correct them as soon as I can, ok?

**Comment by jaflutz** [comment]
Hi @javierm! So sorry for the long delay :-( 
I hope everything is alright now!

**Pull request merged**
