### PR TITLE
UI custom

### PR DESCRIPTION
**Pull request by decabeza**
Objectives
===================
This PR:
- Removes custom content on seeds for official levels names.
- Unifies Spanish investment projects i18n (always use "proyecto de gasto" instead "proyecto de inversión")
- Updates header markup with the last Foundation classes and includes a new logo 🎉 
- Makes footer sticky to bottom (fixing some pages with small height content) and changes footer styles (cleaner with no border and lighter background)

Visual Changes
===================
**New logo on header**
header

**Cleaner footer**
footer

### CODE REVIEW

**Comment by PierreMesure** [comment]
Hey @decabeza, it looks like great work! I have two questions about this:

- in the admin section, the custom logo_header needs to be 80x80, which is too small to include a custom title for the platform (plus a logo). Before, the title of the platform was displayed as text so that wasn't a problem.
- I'm having problems with the cards and the footer but only on Safari (latest). Chrome and Firefox are fine. As you can see, the cards merge vertically and overlap with the footer.
capture d ecran 2018-07-30 a 13 09 29

**Comment by decabeza** [comment]
Hi @PierreMesure!

About the logo, 😅  I just created a PR https://github.com/consul/consul/pull/2819 to fix it (Meanwhile you can update the logo header image manually replacing the file on `app/assets/images/logo_header.png`)

On my browser `Safari Version 11.1.2 (13605.3.8)` (I think is the last) I can't reproduce the issue with the cards, I see them correctly... Do you can provide more information (browser version, window size...) 🤔 

homepage_safari

Thanks! 🙏

**Comment by PierreMesure** [comment]
Sorry, I just checked on a clean consul (with the same database, though) and it doesn't overlap... I don't know yet what causes it but it's my code, not yours...

Another bug that you should be able to reproduce is the CSS leak to the link on the right "See all processes". It's getting the same hover effect as the cards.

capture d ecran 2018-07-31 a 14 11 36

**Comment by PierreMesure** [comment]
One more problem that I just noticed!

capture d ecran 2018-08-01 a 10 59 19

This distorted logo is on the welcome page (localhost:3000/welcome, need to be logged in).

**Comment by aitbw** [comment]
Hi @PierreMesure ! That one was fixed via #2822 :relieved:

**Comment by PierreMesure** [comment]
Damn, you're too fast for me! What about the one above?

**Pull request merged**
