### PR TITLE
Feature close support comments

### LINKED ISSUE #3553: Close supports to comments on Collaborative legislation processes
## What we need
When the debate or drafting phase of a collaborative legislation processes have finished, it should not be allowed to users to vote on the existing comments, as it is not allowed to create new comments.

### PR DESCRIPTION
**Pull request by luchiago**
## References

* Closes #3553 

## Objectives

Close the votes and comments when a draft or debate phase of the collaborative process is done

### CODE REVIEW

**Comment by luchiago** [comment]
Hi @javierm. I have a question. I set like this because I want to get the process from Legislation::Process to see if the draft_phase is open, for example. So how can I associate the :vote action from another controller to process?

**Comment by javierm** [comment]
@luchiago You would have to do something like:

```
cannot :vote, Comment do |comment|
  # Code checking the comment belongs to a process whose phase is closed
end
```

Make sure to add it after the (already present) line saying `can :vote, Comment`, so it doesn't get overwritten :wink:.

**Comment by luchiago** [comment]
@javierm Would be something like this? 
```ruby
      cannot :vote, Comment do |comment|
        !process.draft_phase.open?
      end

      cannot :vote, Comment do |comment|
        !process.debate_phase.open?
      end
```

**Comment by javierm** [comment]
That code would probably fail because the `process` variable isn't defined :thinking:. We'll have to get the process through the `comment` variable :wink:.

It isn't a simple issue, so getting the details right will probably take a few hours/days :relieved:. You'll probably have to check the way comments are related to other models. Make sure to test the changes manually using your browser, too, in order to know whether we're on the right track.

Thank you very much for your time :pray:, and of course if at any moment you don't feel like working on this pull request anymore, feel free to do so :wink:.

**Comment by luchiago** [comment]
> That code would probably fail because the `process` variable isn't defined . We'll have to get the process through the `comment` variable .
> 
> It isn't a simple issue, so getting the details right will probably take a few hours/days . You'll probably have to check the way comments are related to other models. Make sure to test the changes manually using your browser, too, in order to know whether we're on the right track.
> 
> Thank you very much for your time , and of course if at any moment you don't feel like working on this pull request anymore, feel free to say so .

You can reassign this issue for someone else  @javierm, I cannot work on this anymore. Thanks for your time.

**Comment by javierm** [comment]
No problem. Thank *you* for your time :wink:.

**Pull request closed without merging**
