### PR TITLE
Migration from PhantomJS to Headless Chrome

### LINKED ISSUE #2523: Improve test suite, move away from PhantomJS
PhantomJS is dying or near to https://github.com/ariya/phantomjs/issues/15344

Headless Chrome is here to stay

We should do the swap, and maybe in the process we'll get rid of many random failing specs because of JS and phantomjs & flaws

### PR DESCRIPTION
**Pull request by aitbw**
References
==========
* Related issues: #2523, [flaky specs-related issues @ consul/consul](https://github.com/consul/consul/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+flaky) and [flaky specs-related issues @ AyuntamientoMadrid/consul](https://github.com/AyuntamientoMadrid/consul/issues?q=is%3Aissue+is%3Aopen+label%3A%22Flaky+spec%22) —closes #2523 once merged into `master`

* Related PRs: [flaky specs-related PRs @ consul/consul](https://github.com/consul/consul/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+flaky) and [flaky specs-related PRs @ AyuntamientoMadrid/consul](https://github.com/AyuntamientoMadrid/consul/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+flaky)

* Related links:
  * [How GitLab switched to Headless Chrome for testing](https://about.gitlab.com/2017/12/19/moving-to-headless-chrome/)
  * [Switching to Headless Chrome for Rails System Tests](http://technopragmatica.blogspot.com/2017/10/switching-to-headless-chrome-for-rails_31.html)
  * [Flaky tests & Capybara best practices](https://www.simplybusiness.co.uk/about-us/tech/2015/02/flaky-tests-and-capybara-best-practices/)
  * [Ruby Capybara with selenium Cheat Sheat](https://blog.morizyun.com/blog/capybara-selenium-webdriver-ruby/)
  * [Getting Started with Headless Chrome ](https://developers.google.com/web/updates/2017/04/headless-chrome)
  * [Running feature specs with Capybara and Chrome headless](https://drivy.engineering/running-capybara-headless-chrome/)
  * [Headless Capybara Feature Specs with Chrome](https://robots.thoughtbot.com/headless-feature-specs-with-chrome)
  * [Moving From PhantomJS to Headless Chrome in Rails](https://medium.com/@weilandia/moving-from-phantomjs-to-headless-chrome-in-rails-fewer-hacks-simpler-debugging-and-more-c2e2558742c5)
  * [Selenium With Headless Chrome On Travis CI ](http://www.amihaiemil.com/2017/07/14/selenium-headless-chrome-travis.html)

Objectives
==========
* Migrate completely from PhantomJS to Headless Chrome, mitigating entirely **all** flaky specs :tada: 

Notes
=====================
* ~~Just one spec outside of the scope of this PR is failing and it's already fixed at #2522~~
* Had to apply `xscenario` to [this spec](https://github.com/wairbut-m2c/consul/blob/aperez-headless-chrome/spec/features/admin/budget_investments_spec.rb#L656), as it fails randomly (apparently it can't find the browser's alert so it can't accept it —the feature works as expected, though.)

To do
==========
* ~~There are some failing specs that used to work with PhantomJS/Poltergeist because of poor CSS support and poorly implemented specs —[here they are](https://gist.github.com/aitbw/3e818468fb941e410431b7509fb71d68)~~

* ~~**Apparently**, [this spec](https://github.com/consul/consul/blob/master/spec/features/polls/answers_spec.rb#L69) (which is based on [this one](https://github.com/consul/consul/blob/master/spec/shared/features/nested_imageable.rb#L35)) is the last flaky remaining —it has failed just **once** in more than 20 Travis builds; I'll be monitoring this one closely~~

* [This spec](https://github.com/wairbut-m2c/consul/blob/master/spec/features/admin/budgets_spec.rb#L253) works with the `window-size=1200,600` argument for `chromeOptions` or with any resolution if the `headless` flag is removed —while this doesn't affect any other scenarios, it'd be nice to refactor this test for it to work with and without the flag

* [This spec](https://github.com/wairbut-m2c/consul/blob/master/spec/features/admin/banners_spec.rb#L105) works when the `fill_in` steps are reordered to be first —that's because the banner reloads when the elements for customization are out of focus. This gives us room for improvement for this module so we can implement actual live reload

* Since [Decide Madrid](https://github.com/AyuntamientoMadrid/consul) has a bigger codebase / test suite, this PR can't be ported straight away —a different pull request is needed to keep the migration as smooth as possible

* Update [CONSUL docs](https://github.com/consul/docs) accordingly

### CODE REVIEW

**Comment by bertocq** [comment]
I was reading the commit messages and found out you're following some kind of pattern. Following the rules and conventions of the codebase you're it's always the best idea, please rebase them. It's not only about the header line, also about the lack of body description

Some resources to learn about good commit messages:
- https://github.com/GitInPractice/GitInPractice/blob/master/12-CreatingACleanHistory.adoc
- https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
- https://brainlessdeveloper.com/2018/02/19/git-best-practices-atomic-commits/
- https://github.com/torvalds/subsurface-for-dirk/blob/master/README#L92-L119
- https://sethrobertson.github.io/GitBestPractices/#enforce

**Comment by aitbw** [comment]
Rebased commits, @bertocq. Added description to only 2 commits as the commit messages alone were not descriptive enough.

**Comment by aitbw** [comment]
As today (16/03/2018), the migration from PhantomJS/Poltergeist to Headless Chrome/Selenium is 100% complete :tada:

**Comment by voodoorai2000** [comment]
Awesome @aitbw! 👏🎉

**Comment by bertocq** [comment]
@aitbw 

This is not working locally at macos as running a single spec (or multiple) throws errors like:
```
  1) Notifications Mark as unread
     Failure/Error: visit root_path

     Selenium::WebDriver::Error::WebDriverError:
       unable to connect to chromedriver 127.0.0.1:9516
     # ./spec/features/notifications_spec.rb:9:in `block (2 levels) in <top (required)>'
```
Should we include any tips/guidelines at readme file to make this work?

**Comment by aitbw** [comment]
Oh sorry about that @bertocq! On Mac OS you need to run `brew install chromedriver` first

I'll be updating the [consul/docs](http://github.com/consul/docs) later today with all this information

**Pull request merged**
