### PR TITLE
User recomendations

### PR DESCRIPTION
**Pull request by taitus**
Where
=====
* **Related PR's:** #1776 

What
====
Show recommended proposals and debates to logged in users based in their interests.

How
===
**Admin**
Allow recommended module activation/deactivation on global settings form admin panel. Added new Setting key “feature.user.recommendations” to achieve this. Maybe some forks do not need this feature.

**FrontEnd**
1. Display user recommendations (Debates and Proposals) on Home page only when user is logged
  1.a Use user interests if any (tags from followed objects) to get best user recommentations sorted by votes count
  1.b Discard already followed object from recommendations
2. Add link to home recommendations to go to filtered index
3. Add new settings "feature.user.recommendations" 
4. Add new “Recommended” search filter to Proposals and Debates index pages.

Screenshots
===========
- Partial recommendeds and link (1, 2)
Home with recommendations

- Admin Panel (3)
Global settings with feature recommendations

- Recommendations filter (4)
New filter on Debate index

Test
====
- Check display recommendations on Home page (by user logged, admin settings and results)
- Check order by votes on recommendations methods (Proposal and Debate)
- Check recommendations results are related with user interests
- Check recommendation filter is compatible with search by terms

Deployment
==========
Remember we added next settings:
- seeds: `Setting['feature.user.recommendations'] = nil`
- dev_seeds: `Setting.create(key: 'feature.user.recommendations', value: "true")`

### CODE REVIEW

**Comment by bertocq** [comment]
Hey @taitus ! Sorry for the review delay 🙇  we're a bit tight on time and catching back with pending stuff. I've just solved the merge conflicts that this PR had and will keep and eye on the travis build (and check the huge code changes as well as soon as possible 😄 ) Your contributions are much appreciated as always!! Thanks ❤️

**Comment by Senen** [comment]
Hi @agileontheweb , can you take a look to a little error on home user recommendations? Check proposals recomendation carousel bullets on screenshot below. I also changed image version from :thumb to :medium (300pxx300px) on recommendations, check this feature on responsive versions please 🙏 

captura de pantalla 2017-09-28 a las 12 55 54

**Comment by agileontheweb** [comment]
Hi @Senen , i tested it for Safari, Firefox, Chrome, Opera.

I fixed only two style. Nothing special.
Add some screen.

**Before &darr;**
The content does not have the same width as the image (title and description). 

**Smartphone**
before

**Desktop**
Bullets are not aligned.

before-desktop

**After &darr;**
Now the content has the width of the image, better view.
Bullets are aligned.

**Iphone-4**
captura de pantalla 2017-09-28 a las 17 05 12

**Iphone-6 plus**
captura de pantalla 2017-09-28 a las 17 04 56

**Ipad-landscape**
captura de pantalla 2017-09-28 a las 17 04 23

**Ipad-portrait**
captura de pantalla 2017-09-28 a las 17 06 52


**Desktop Opera**
captura de pantalla 2017-09-28 a las 17 04 08

**Desktop Firefox**
firefox

**Desktop Safari**
safari

**Desktop Chrome**
chrome

**Comment by voodoorai2000** [comment]
Excellent! 
Thank you @Senen, @taitus, @agileontheweb 👌 🙏 🎉

**Pull request merged**
