### PR TITLE
Solves #3153. It refactors images attributes.

### PR DESCRIPTION
**Pull request by rogelio-o**
## References

Refactor image attributes #3153

## Objectives

Define those attributes in only one place, and reuse them everywhere they're used.

### CODE REVIEW

**Comment by javierm** [comment]
@rogelio-o Thank you very much for this pull request! :heart_eyes:

There's only one thing I can think about which would make this pull request even better. Including `ImagesHelper` would include all its methods (like `image_absolute_url`) in these controllers, and it would also make the `image_attributes` available in the view layer.

What do you think about moving the `image_attributes` method to a controller concern (maybe in a file like `app/controllers/concerns/image_attributes.rb`) so there are no side effects?

**Comment by rogelio-o** [comment]
Sure! You're right, it's better to move it!

**Comment by rogelio-o** [comment]
Great! Thanks!

**Comment by javierm** [comment]
Merged! :tada: Thank you very much @rogelio-o! :smile:

**Pull request merged**
