### PR TITLE
Add cs icon of SDGs

### PR DESCRIPTION
**Pull request by trendspotter**
## References

> Related Issues/Pull Requests/errors/etc...

## Objectives

> What are the objectives of these changes?

## Visual Changes

> Any visual changes? please attach screenshots (or gifs) showing them.
> If modified views are public (not the admin panel), try them in mobile display (with your browser's developer console) and add screenshots.

## Notes

> Mention rake tasks or actions to be done when deploying this changes to a server (if any).
> Explain any caveats, or important things to notice like deprecations (if any).

### CODE REVIEW

**Comment by javierm** [comment]
Ahoj, @trendspotter :smile:.

(It's been 15 years since I lived in Brno, so I'm afraid that's everything I can say in Czech right now :sweat_smile:).

I've taken the liberty to create the [sdg_cs branch](https://github.com/consul/consul/tree/sdg_cs), which squashes the commits (so the big goal 12 file isn't in version control and we keep the repository size as small as possible) and adds the icons in 200x200 so they're consistent with the other languages. Would you mind updating your branch so it has the same contents as the sdg_cs branch?

Děkuji moc!

**Comment by javierm** [comment]
@trendspotter Sorry, I didn't properly express what I meant :pray:.

Could you try running these commands?

git remote add upstream https://github.com/consul/consul.git
git checkout master -b sdg_cs
git fetch upstream sdg_cs
git reset --hard upstream/sdg_cs
git push

And then open a new pull request from your `sdg_cs` branch to our `master` branch.

Thank you very much! :pray:

**Comment by trendspotter** [comment]
New pull request opened as #4782.

**Comment by javierm** [comment]
Cool, thanks! Closing in favor of #4782.

**Pull request closed without merging**
