### PR TITLE
Show active tab in custom info texts

### PR DESCRIPTION
**Pull request by papayalabs**
References
===================
Issue [#2889](https://github.com/consul/consul/issues/2889)

Objectives
===================
Fix Issue [#2889](https://github.com/consul/consul/issues/2889)

Visual Changes
===================
**Before:**
When you select a tab it does not active title in blue and underlined.
screen shot before

**After:**
When you select a tab it does active title in blue and underlined.
screen shot after

### CODE REVIEW

**Comment by aitbw** [comment]
Hi @papayalabs, just one small thing I'd like you to address: can you fix the small typo on the PR's title as well as on the commit message?

If you could also add a before/after screenshot comparison, that'd be great as well :smile_cat:

Thanks once again for collaborating with CONSUL :tada:

**Comment by papayalabs** [comment]
Hi @aitbw, of course! no problem to add before/after screentshots. But what do you mean with 'small typo', I don´t get it sorry. Please clarify it and I will fix it!

**Comment by aitbw** [comment]
Oh sorry @papayalabs, I missed that one :sweat_smile: `custon` for `custom` :ok_hand:

**Comment by papayalabs** [comment]
Hi @decabeza, sure I will fix the indentation using two spaces! 🙏 Thanks for change the PR titles!

**Comment by voodoorai2000** [comment]
@papayalabs thank you for this fix! 🎉

Could you add a simple spec to make sure it doesn't bite us again in the future? 😌

[Here](https://github.com/consul/consul/blob/master/spec/features/admin/site_customization/information_texts_spec.rb#L51) would be a good place to add it 👌

**Comment by papayalabs** [comment]
@voodoorai2000 Of course! I already added! :)

**Comment by voodoorai2000** [comment]
Fabulous! Thank you @papayalabs! 🙌

**Pull request merged**
