### PR TITLE
Add ability to keep GET params in return URL

### LINKED ISSUE #4024: Return URL after "Sign in" doesn't keep GET params.
### User Story
After "Sign in" action, as a user, I want to be redirected to the same page where I was before "Sign in".

### Why is this Needed?

**Step 1:** At the current moment on page https://demo.consulproject.org/budgets page we have listed budget pages with budget links that lead to URLs with `heading_id` like: https://demo.consulproject.org/budgets/1/investments?heading_id=4
image

**Step 2:** You visit URL with `heading_id` param and clicking to "Sign in" button to be authorized

After you got successful authorization you will be redirected to page `https://demo.consulproject.org/budgets/1/investments` without `heading_id` param

So you getting another page that you had before "Sign in" action.

### Description
*Type*: Bug

### Current Behavior
After Sign in consul redirects you to URL without get params

### Expected Behavior
After Sign in consul redirects you to exactly the same URL you where before.

### Steps to reproduce
1. Visit page https://demo.consulproject.org/budgets
2. Select specific budget to see https://demo.consulproject.org/budgets/1/investments?heading_id=4
3. Click "Sign in" and type login/pass
4. After Sign in consul redirects you to https://demo.consulproject.org/budgets/1/investments

### PR DESCRIPTION
**Pull request by andriyun**
## References

* Closes #4024 

## Objectives
Get support for GET params for return URL

## Visual Changes
None

### CODE REVIEW

**Comment by andriyun** [comment]
Is there anyone who could help me find out what it wrong with travis build?

I don't understand how return URL path could affect homepage
image

**Comment by Senen** [comment]
Hi @andriyun, seems to be a flaky spec, probably (almost sure) it is not related with your changes. Also that spec succeed when running locally so you do not have to worry! We are working on solving flaky specs issues.

**Comment by andriyun** [comment]
Thank you for reply @Senen .

Then next step for this PR to get accepted by reviewer :)

**Comment by javierm** [comment]
@andriyun Thank you for this pull request! :smile:. Would it be possible to add a test so we get a failure if we accidentally undo these changes? :pray:

By the way, it would be great if you used `amend` instead of adding a new commit for the test :wink:.

The test that's failing started failing recently after the release of Chrome 83. It will be fixed by pull request #4023. Sorry for the inconvenience!

**Comment by andriyun** [comment]
Thanks for feedback.
I'm not Ruby developer. So I don't think it will be affordable for me to write test.
But you could list here some ideas or similar test cases with info how it should look like.
Maybe there will be someone who could make it :)

**Comment by javierm** [comment]
Thanks, it's nice that you took the time to investigate the issue and find a fix even if you aren't a Ruby developer :smile:.

We're now dealing with a few other pull requests; we'll try to write a test case for this one in a few weeks. In the meantime, if someone wants to give it a go, they're welcome :wink:.

**Comment by javierm** [comment]
@andriyun I've added the test and opened pull request #4079. You still appear as the author of the commit, of course :smile:. Thanks a lot for the fix!

Closing in favor of #4079.

**Pull request closed without merging**
