### PR TITLE
Minor improvements in dev seeds

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Where
=====
* **Related Issue:** None

What
====
Improve dev seeds in to ways:
* Normalize output.
* Add an unverified user to make testing the verification process more straighforward.

How
===
* Normalize output: Change `puts` with `print` like it's done in the rest of the `dev_seeds.rb` file.
* Add an unverified user creation to `dev_seeds.rb`.

Screenshots
===========
None.

Test
====
Run seeds, check that the output is a bit nicer, and that an unverified user is created.

Deployment
==========
As usual.

Warnings
========
None.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I don't know why this didn't trigger a new build. Maybe it's because I forked the repo back when it was called "participación"? I updated & renamed it but it didn't change a thing, maybe I have to open a new PR from the updated repo...

**Comment by bertocq** [comment]
Sorry @deivid-rodriguez but @travis-ci is [under scheduled maintenance](https://www.traviscistatus.com/) right now :). I'll keep an eye on the PR for when we can trigger it again manually or ping you to do a:
```bash
git commit --amend --no-edit
git push -f
```

That usually does the trick for me

**Comment by deivid-rodriguez** [comment]
Aaaaah, I see, good catch! Yep, I'll retrigger the build when you ping me!

Ah, since I got your attention, would you review https://github.com/consul/website/pull/5? Should be an easy one :)

**Comment by deivid-rodriguez** [comment]
It didn't pass but looking at other PR's and at the failure, this looks like unrelated build flakyness?

**Comment by deivid-rodriguez** [comment]
Rebased it and it's passing now! :smile:

**Pull request merged**
