### PR TITLE
Add Spring binstubs for RSpec

### PR DESCRIPTION
**Pull request by josepjaume**
This adds `spring` binstubs for `RSpec`, which helps transparently use spring when using tests.

### CODE REVIEW

**Comment by voodoorai2000** [comment]
Thank you @josepjaume :+1:

**Comment by josepjaume** [comment]
Just trying to get a llitle street cred here :dancer:. Let's keep in touch!

**Comment by voodoorai2000** [comment]
You already have it :) Inviting you to a Slack channel shortly!

**Comment by josepjaume** [comment]
Yaaay! Lots of stuff to talk about!

**Pull request merged**
