### PR TITLE
Add the ability to import local census records through a CSV file

### PR DESCRIPTION
**Pull request by Senen**
## References

Related Issues: #3478 
Related Pull Requests: This PR includes #3479 

## Objectives
Allow administrator users to import local census records though CSV file.

## Visual Changes
**Link to new importation**
local-census-records-link-to-new-importation

**Admin settings menu**
admin-menu

**Importation form (local_census_records/importations#new)**
local-census-record-importation-form

**Importation results page (local_census_records/importations#show)**
local-census-records-importation-validation-errors

local-census-records-importation-success

## Notes
None

### CODE REVIEW

**Comment by Dr4u95** [comment]
@decabeza When creating a .csv file, the entire database is usually passed.

If it is the first time it is passed there will be no problems, but if there is already one, it will duplicate the data.    

I think document_number should be a primary key in the table, for no have these issues.

**Comment by Senen** [comment]
As @Dr4u95 says, now is possible to create duplicated records (😬) if you import same file more than once. Maybe we should add an uniqueness database constraint and a uniqueness model validation for `[:document_type, :document_number]` pair.

So, what do you think @voodoorai2000?

**Comment by voodoorai2000** [comment]
> Maybe we should add a uniqueness database constraint and a uniqueness model validation for `[:document_type, :document_number]` pair.

+1 👌

**Comment by Senen** [comment]
@Dr4u95 we added a database contraint and a uniqueness validation for :document_number and :document_type pair. Thx for your help 🤗

**Comment by Dr4u95** [comment]
@Senen Nice, that's works perfect

Another thing that I have noticed, is that when you verify an account, although after you delete it from the census, the user remains as verified member.
It can be useful in cases where the member moves to another city. Maybe I should open a new issue about it

**Comment by Senen** [comment]
Hi @Dr4u95 , thanks fot test this feature again! Im glad it's working well. 👌 

In reference to the users that have changed their residence i really don't know if the application currently cover this need in any way, but it sounds like something so important to have its own issue to discuss posible solutions and we can also cover how to proceed in the same case but when you are using a remote census service. 🤔 

Maybe @consul/core has something to say here!

**Comment by voodoorai2000** [comment]
Hey @Dr4u95, @Senen,

Sure, this is a feature that has been requested, we have an [open issue](https://github.com/consul/consul/issues/1887). 😌
Feel free to give a 👍 to the issue, we'll try to get it rolling again. 😉

**Comment by Senen** [comment]
Travis job has no failures, a timeout exception was thrown.

`The job exceeded the maximum time limit for jobs, and has been terminated.`

**Pull request merged**
