### PR TITLE
Admin tables order - sorting [#2931]

### PR DESCRIPTION
**Pull request by matisnape**
## References

Issue: Admin tables order #2931

## Objectives

- remove sort select for Budget Investments
- implement sorting in columns: ID, Title, Supports
- submit first OSS PR :D 

## Visual Changes

- removed sort_by select
- added arrow icon to indicate sorting direction

image

## Notes

- modified tests to support new sorting rules
- fixed a bug with unsupported sort_by values (e.g. edited manually in the address field) - now the controller just ignores it and returns all investments
- I've created 3 helper methods for sorting in Budget Investments Helper for the sake of this PR, but eventually I think it should become a separate helper or module for sorting, which would also contain the model method self.order_filter - let me know which strategy you would like me to follow.

This is my first ever external commitment and I don't have commercial experience, so I figure there is a lot to refactor. I'd be happy to do that after code review :) Just point everything I could improve and I'll do my best :) I'd also would like to implement sorting for other tables as well so I'd appreciate any guidance towards making this more reusable.

### CODE REVIEW

**Comment by matisnape** [comment]
I think it's pretty much it. Let me know what you think so far :)

**Comment by javierm** [comment]
@matisnape Thank you very much for this pull request! :trophy:

It looks like there are conflicts with our current `master` branch. Since you've so generously worked on this issue during your holidays :heart:, we felt taking up more of your time by asking you to deal with these conflicts (which were caused by us) wouldn't be so kind from our side.

So we've opened a new branch rebasing your changes against current `master` and fixing a couple of minor issues: https://github.com/consul/consul/tree/rebased_budget_investments_sorting_columns

In order to update this pull request, run the following commands:
```
git remote add upstream https://github.com/consul/consul  
git fetch upstream rebased_budget_investments_sorting_columns
git checkout budget_investments_sorting_columns
git reset --hard upstream/rebased_budget_investments_sorting_columns
git push -f
```
Then we can merge it into master :smile:.

**Comment by javierm** [comment]
@matisnape That would be awesome! Thank you so much :pray:!

In order to make the code more reusable, you can try one of these approaches:

1. Make all table headers on this table sortable (which might prove quite a challenge in some cases)
2. Add sortable headers to another table

Once we do similar tasks in a couple of places, it's easier to find ways to reuse the code :smile:.

**Comment by matisnape** [comment]
@javierm 

> Add sortable headers to another table 

You mean new table in database?

**Comment by javierm** [comment]
I mean another table (`<table>` HTML tag) in the admin section :wink:

**Comment by matisnape** [comment]
@javierm done! :)

**Comment by javierm** [comment]
@matisnape Thanks a lot!

**Comment by matisnape** [comment]
I'll start working on adding sorting in other places :)

**Pull request merged**
