### PR TITLE
Issue #1901: Budget related entries in Management shouldn't appear if budgets are globally disabled

### PR DESCRIPTION
**Pull request by periflo90**
Where
=====
* **Related Issue:** #1901

What
====
Checks if the Budget setting is enabled, and if not, does not render its related entries in the Management menu.

How
===
Three if clauses which check against the Budgets setting.

Screenshots
===========
screenshot

### CODE REVIEW

**Comment by decabeza** [comment]
Hi @periflo90! Thanks for the PR! 👍 

I think you can use only one `<% if Setting['feature.budgets'] %>` to wrap the three links related to budgets. Feel free to move them 😉

**Comment by periflo90** [comment]
@decabeza I could wrap the first two list items under the same if clause, but the last one had two other items in between, so I left that one under a different if clause.

**Comment by decabeza** [comment]
As I indicated, you can move al links inside only one if 😉 

```ruby
<% if Setting['feature.budgets'] %>
      <li <%= "class=active" if (controller_name == "budget_investments" && action_name == "new") ||
                                (controller_name == "budget" && action_name == 'create_investments') %>>
        <%= link_to create_investments_management_budgets_path do %>
          <span class="icon-budget"></span>
          <%= t("management.menu.create_budget_investment") %>
        <% end %>
      </li>

      <li <%= "class=active" if (controller_name == "budget_investments" && action_name == "index") ||
                                (controller_name == "budget" && action_name == "support_investments")%>>
        <%= link_to support_investments_management_budgets_path do %>
          <span class="icon-like"></span>
          <%= t("management.menu.support_budget_investments") %>
        <% end %>
      </li>

      <li <%= "class=active" if (controller_name == "budget_investments" && action_name == "print") ||
                                (controller_name == "budgets" && action_name == "print_investments") %>>
        <%= link_to print_investments_management_budgets_path do %>
          <span class="icon-print"></span>
          <%= t("management.menu.print_budget_investments") %>
        <% end %>
      </li>
    <% end %>
```

**Comment by periflo90** [comment]
But, wouldn't that affect the order of the menu items? Would that be OK with you? If so, I could do it.

**Comment by decabeza** [comment]
It's better follow DRY principle than the order menu 😛 moreover I think also it's better than all the related items are together.

So yes, you can change the order 😉 

Thanks! 🙏

**Comment by periflo90** [comment]
Okay, done. I hope everything's okay.

**Pull request merged**
