### PR TITLE
Improve community

### PR DESCRIPTION
**Pull request by taitus**
Where
=====
* **Related PR's:** #1815 

What
====
- Some improvements and code refactor.
- Add destroy action on topics controller.

Screenshots
===========
- Display destroy button when user logged is an author from topic.
destroy button

Test
====
- As usual

Deployment
==========
- As usual

Warnings
========
- None

### CODE REVIEW

**Comment by voodoorai2000** [comment]
This is marvellous! 
Much cleaner :))

Appreciate it @taitus!

**Comment by josephmartz** [comment]
superb <3

**Comment by bertocq** [comment]
👏  @taitus ‼️

**Comment by taitus** [comment]
🎉 🎉 🎉

**Pull request merged**
