### PR TITLE
Upgrade Ruby to version 3.0.6

### PR DESCRIPTION
**Pull request by javierm**
## References

* Depends on #5089

## Objectives

* Update Ruby to a more recent version

## Notes

These were the gems we're currently using whose compatibility with Ruby 3 we hadn't confirmed yet. They're all confirmed now.

* ~autoprefixer-rails~
* ~byebug~
* ~capistrano-bundler~
* ~capistrano-rails~
* ~capistrano3-delayed-job~ (no updates since January 2019)
* ~capistrano3-puma~
* ~ckeditor~
* ~cocoon~
* ~email_spec~ (no release since April 2018)
* ~erb_lint~ (pull request #5093)
* ~foundation-rails~ (has almost no Ruby code, so it might work)
* ~graphiql-rails~ (has almost no Ruby code)
* ~initialjs-rails~
* ~jquery-ui-rails~ (has almost no Ruby code, so it might work even if there haven been no updates since January 2017)
* ~mdl~ (support in version 0.12 for sure)
* ~omniauth-twitter~ (no updates since February 2017)
* ~pronto-erb_lint~ (pull request #5093)
* ~puma~
* ~rinku~ (no updates since April 2019)
* ~rvm1-capistrano~ (no updates since October 2015)
* ~sassc-rails~ (no updates since December 2019)
* ~scss-lint~
* ~selenium-webdriver~
* ~spring~
* ~spring-commands-rspec~ (no updates since March 2015)
* ~turbolinks~ (unmaintained, but it's mostly written in CoffeeScript and might work)
* ~turnout~ (no updates since December 2018)

### CODE REVIEW

**Comment by Senen** [comment]
Hi @javierm,

Capistrano seems to work fine with Ruby 3. I tested it by doing the following:
* Created a new virtual machine with Ubuntu 20.04
* Run the installer in it, so it installs the 1.5.0 version
* From the ruby3.0 branch, I deployed the master branch, which installs Ruby 2.7.7 in the server
* From the ruby3.0 branch, I deployed the ruby3.0 branch to the server which installs Ruby 3.0.5 in the server

Everything worked fine 👌🏼 .

**Comment by Senen** [comment]
> @Senen Great!
> 
> Regarding the installer, I think the only thing left would be installing the `ruby3.0` branch on an empty machine, and if it works we could also mark `autoprefixer-rails` (if it adds the prefixes), `puma` and `sassc-rails` 🤔.

Everything worked fine! 

Here is a piece of the compiled CSS that demonstrates autoprefixer works:
```
.feed-debates{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;margin-top:1.5rem;-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column}
```

Regarding `sassc-rails` and puma nothing to comment on, everything seems to work fine.

Below are the post-install messages the server throws after bundling:
```
Bundle complete! 102 Gemfile dependencies, 176 gems now installed.
    Gems in the groups 'development' and 'test' were not installed.
    Bundled gems are installed into `/home/deploy/consul/shared/bundle`
    Post-install message from ancestry:
    Thank you for installing Ancestry. You can visit http://github.com/stefankroes/ancestry to read the documentation.
    Post-install message from rubyzip:
    RubyZip 3.0 is coming!
    **********************
  
    The public API of some Rubyzip classes has been modernized to use named
    parameters for optional arguments. Please check your usage of the
    following classes:
      * `Zip::File`
      * `Zip::Entry`
      * `Zip::InputStream`
      * `Zip::OutputStream`
  
    Please ensure that your Gemfiles and .gemspecs are suitably restrictive
    to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).
    See https://github.com/rubyzip/rubyzip for details. The Changelog also
    lists other enhancements and bugfixes that have been implemented since
    version 2.3.0.
    Post-install message from sass:
  
    Ruby Sass has reached end-of-life and should no longer be used.
  
    * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
      primary implementation: https://sass-lang.com/install
  
    * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
      sassc gem: https://github.com/sass/sassc-ruby#readme
  
    * For more details, please refer to the Sass blog:
      https://sass-lang.com/blog/posts/7828841
  
    Post-install message from oauth2:
  
    You have installed oauth2 version 1.4.10, which is EOL.
    No further support is anticipated for the 1.4.x series.
  
    OAuth2 version 2 is released.
    There are BREAKING changes, but most will not encounter them, and upgrading should be easy!
  
    Please see:
     https://github.com/oauth-xx/oauth2#what-is-new-for-v20
     https://github.com/oauth-xx/oauth2/blob/master/CHANGELOG.md
  
    Please upgrade, report issues, and support the project! Thanks, |7eter l-|. l3oling
  
    Post-install message from rails-assets-leaflet:
    This component doesn't define main assets in bower.json.
    Please open new pull request in component's repository:
    https://github.com/Leaflet/Leaflet
```

1. Our current `scss_lint` version depends on the sass gem, which reached its EOL. It seems [there is no plan to upgrade the scss_lint gem](https://github.com/sds/scss-lint#notice-consider-other-tools-before-adopting-scss-lint).
2. Not sure what mean the leaflet-related message; we should test if the map keeps working in production. Added to the list of gems to check.

**Comment by javierm** [comment]
@Senen Awesome!

These messages appear when installing these gems with Ruby 2.7.x as well, so there shouldn't be an issue with this upgrade :crossed_fingers:.

**Review by Senen — COMMENTED** [review]
I think we are ready to go @javierm, @taitus 👏🏼 ! Or are there more things to test 🤔 ?

**Comment by javierm** [comment]
@Senen Great! :smile:

That's all for now, but let's leave it as a draft until we decide whether we include it in version 2.0.0.

You can approve it, though.

**Review by Senen — APPROVED** [review]

**Pull request merged**
