### PR TITLE
Make it clearer when a proposal was created "on behalf of" someone else

### LINKED ISSUE #3696: Make it clearer when a proposal was created "on behalf of" someone else
### User Story

As a participatory budget organiser, we allow people to leave proposals physically in a box in the public library. We also organise several physical events during which people can contribute with ideas but we don't necessarily make them create an account and add their projects on the platform.

As a participatory budget organiser, I want to be able to create proposals and budget investments on behalf of someone and that the identity of that person be clearly visible.

Currently, it is possible to add a proposal on behalf of a group or an organisation and this works perfectly fine for our use case as well:

What we would like to improve is the visibility of the proposal author's name in the list of proposals and on the proposal's page.

### Why is this Needed?

To make sure that there is no misunderstanding and so it doesn't look like a majority of the proposals have been left by the admin.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

#### Creation form

Capture d’écran 2019-09-12 à 09 01 58

#### Proposal page
You can then see that the proposal was written on behalf of someone at the bottom:

Capture d’écran 2019-09-12 à 09 00 48

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Capture d’écran 2019-09-12 à 09 06 55

Capture d’écran 2019-09-12 à 09 12 04

### Definition of Done
- text present in the list view
- text present in the proposal view
- (optional) change the avatar letter so it matches the proposal author and not the one who wrote it on behalf
- (optional) remove the text at the bottom of the proposal which is quite confusing currently

### PR DESCRIPTION
**Pull request by matisnape**
## References

* Closes #3696

## Objectives

Make it clearer when a proposal was created "on behalf of" someone else

## Visual Changes

As described in the original Issue

## Notes

Should I update the tests to check if the real proposal author is displayed in different place? Currently it checks only the presence on the whole page.

### CODE REVIEW

**Comment by matisnape** [comment]
@javierm 
BTW, I found 2 bugs on master when I create a new investment as admin

visual in route /management/budgets/:id/investments/new https://monosnap.com/file/fHqPiDojfRwjFUaPjoQQ9K1q105a0f
some problem with partial in Management http://localhost:3000/management/budgets/:id/investments/:id https://monosnap.com/file/AKU4LfRFVhEn1bmNAcGTrbS4aYOdLh
Are you aware of those? If you can reproduce, can I create a new issue and try to fix it? I see that budget_investments_spec.rb and proposals_spec.rb are passing, but I'm not sure why

**Comment by javierm** [comment]
@javierm Thanks for reporting! :smile: The first bug was introduced this week and will be fixed by #3749

We're aware of the second bug too (not sure if there's an issue for it :thinking:, although #2855 is similar). It happens when you try to create an investment as a manager before selecting a user, if I'm correct.

I'd finish this pull request before starting to work on the other one :wink:.

**Comment by matisnape** [comment]
@javierm I don't quite get the Travis config, but one of the jobs failed in the build (timed out). I don't know if it's a random fail or I did something wrong and I believe I cannot trigger a rebuild

**Comment by javierm** [comment]
Lately that's quite unusual :thinking:. You can try triggering a rebuild (sort of) by executing `git commit --amend` and `git push -f` :wink:.

**Comment by matisnape** [comment]
@javierm Another fail :( I checked twice if there's no byebug left, so I really don't know why the build times out :(

**Comment by javierm** [comment]
@matisnape It didn't timeout this time, though :wink:. There seems to be a failure because of unused keys: https://travis-ci.org/consul/consul/jobs/597458481#L1276

**Comment by javierm** [comment]
@matisnape Thanks for this pull request! :smile: I'll have a look at it, hopefully next week.

In the meantime, could you add a test for the scenario we're trying here? :pray: This way we'll know it works properly and we'll be notified if it ever stops working.

**Comment by matisnape** [comment]
@javierm I asked about that in notes - there's a test for that, but only for presence of the phrase on the whole page. Should I write the test for the exact place where it's displayed?

**Comment by javierm** [comment]
@matisnape You're totally right; I missed the notes :sweat_smile:.

In general, we need to write a test which fails without this pull request but passes thanks to the changes in this pull request.

**Comment by javierm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
