### PR TITLE
Rails5 all tests passing

### PR DESCRIPTION
**Pull request by alejanderl**
All tests are passing and deprecation warnings are fixed.
Still left some deprecation warnings coming from gems like `invisible_captcha`

### CODE REVIEW

**Comment by alejanderl** [comment]
@voodoorai2000  I have green on my fork but there's a failure with a route helper in the PR. I'm trying to figure out the problem.

**Comment by voodoorai2000** [comment]
Awesome @alejanderl !!!

Try adding the option `as: "root"` to the route in
https://github.com/consul/consul/blob/master/config/routes.rb#L355

**Comment by alejanderl** [comment]
Thanks for the input @voodoorai2000 .
The line of the failure
`app/views/shared/_admin_login_items.html.erb:29`
is not existing in my branch
https://github.com/alejanderl/participacion/blob/rails5/app/views/shared/_admin_login_items.html.erb.
So neither the line 355 in routes as there's no `namespace :officing` in my
https://github.com/alejanderl/participacion/blob/rails5/config/routes.rb
I guess is something cache wise related with travis. Could you try to flush the caches in travis? ;)

**Comment by voodoorai2000** [comment]
OMG we have a green light!

Thank you so much @alejanderl ! :raised_hands:

Closes https://github.com/consul/consul/issues/784

**Pull request merged**
