### PR TITLE
Use PhantomJS version 2.1.1 in TravisCI

### PR DESCRIPTION
**Pull request by amaia**
As described here https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-200965782

### CODE REVIEW

**Comment by amaia** [comment]
@kikito as we talked yesterday, it still fails, but maybe in a different way that could be a starting point to fix the flaky tests

**Comment by xuanxu** [comment]
(Travis builds relunched to check if those failing specs are flaky)

**Comment by kikito** [comment]
I have found an [issue which seems to be related](https://github.com/teampoltergeist/poltergeist/issues/677#issuecomment-222919584). Apparently, the "can't reach server" error happens when your asset pipeline compilation is not fast enough - rails is trying to do it "on the fly" on the first test, and capybara times out. So the "server unreachable" error might be fixed if we compile the assets before launching the specs.

**Comment by amaia** [comment]
I'm closing this one, as it doesn't solve the errors, and #1364 already improved the flaky specs thing a lot.

**Pull request closed without merging**
