### PR TITLE
Ckeditor4 update

### PR DESCRIPTION
**Pull request by javierm**
**NOTE**: continuing #2854 since Raúl isn't available anymore. Everything here is copied from there and was written by @raul-fuentes.

# References

* Issue #2495

# Objectives

Update ckeditor4 configuration adding headings, links and images

# Visual Changes (if any)

- Interface
captura de pantalla de 2018-08-14 14-03-55

- Changing heading
peek 14-08-2018 14-05

- Adding a link
peek 14-08-2018 14-05-8

- Adding an image
peek 14-08-2018 14-07-9

# Notes

* There are no feature specs checking image attachments in CKEditor. I haven't figured out the whole process of clicking the image button in the editor and then filling in all necessary fields in the popup, clicking the access server button in that popup, which opens another popup, ...

### CODE REVIEW

**Comment by decabeza** [comment]
It seems necessary to change `<%= text_with_links @custom_page.content %>` to `<%= @custom_page.content.html_safe %>` on `/views/pages/custom_page.html.erb` to render the CKEditor content correctly 🤔

**Comment by PierreMesure** [comment]
Hey, it’s great to have you guys back from holiday (at least you @decabeza)!

I’d appreciate if you could consider my request to not merge this befor testing has been done with external file storage such as S3. I’m not sure I’ll have time to do that next week though. But I wrote a neat tutorial to configure S3 in Consul, it’s in a PR in the docs.

**Comment by voodoorai2000** [comment]
Nice work! @raul-fuentes, @javierm 👍🎉

**Comment by voodoorai2000** [comment]
Hey @PierreMesure,

We would love to make you happy and not merge this PR until it's nicely integrated with S3
But... we have other forks pressing to merge it too...

We don't think it will stop the other features from working in Heroku... nor raise other exceptions in the other Ckeditor features, if it does please let us know and will fix that right away

Creating a [new issue](https://github.com/consul/consul/issues/2904) to integrate CKeditor with S3, hopefully a nice soul will help us out with this soon 😌Otherwise we'll try and find some time to implement it

**Comment by PierreMesure** [comment]
No problem! I'll test before upgrading and fix what needs to be fixed before (and submit a PR). It doesn't seem like anyone uses S3 at the moment and I'll gladly ditch it myself whenever I can.

**Pull request merged**
