### PR TITLE
Allow admins to download Newsletter's users emails list in zip

### PR DESCRIPTION
**Pull request by bertocq**
## Where & What
This tries to close https://github.com/consul/consul/issues/1488 that just asks to merge existing feature from Madrid's fork added in PR https://github.com/AyuntamientoMadrid/consul/pull/157

## How
Carefully cherry-pick fork's commits (to preserve authorship's).

screen shot 2017-05-23 at 18 31 52

>You get the page:

screen shot 2017-05-23 at 18 31 38

## Test
Will cover new code with test, work in progress (I just got specs to pass locally after realizing a my mistake on Gemfile.lock changes)

### CODE REVIEW

**Comment by bertocq** [comment]
@xuanxu lets wait a bit before merging, I'm still having issues trying to get all tests to pass locally (I think I've messed up installed gem versions during cherry-pick of the first commit).

Also I'll write a test to cover that new feature, I just need some time to get rolling with the codebase

**Comment by xuanxu** [comment]
👍 no problem!

**Comment by bertocq** [comment]
Nah its not a gem problem, it just remembered it's phantomjs version problem I had a year ago  https://github.com/consul/consul/pull/1039#issuecomment-205783702 but ended up giving up on fixing that issue :(. 

Somehow I can't install PhantomJS 1.9.8 with `brew install phantomjs@1.98` returns:
```
$ : brew install phantomjs@1.98
phantomjs@1.98: This formula either does not compile or function as expected on macOS
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

I've tried direct download from https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip but putting the binary at `/usr/local/bin/phantomjs` and ensuring its executable still ends me up with errors (`The detector #<struct Cliver::Detector command_arg=nil, version_pattern=nil> failed to detect theversion of the executable at '/usr/local/bin/phantomjs'`) and  that's another rabitthole to explore 🙈

**Comment by bertocq** [comment]
Okey @xuanxu I think I got a nice & clean way to test the newsletter zip file content, implemented with https://github.com/consul/consul/pull/1557/commits/9ba29fef8cc0b5abb283d840d03e8d064643d0e8#diff-4dc53c1410e5da9303b4ae31334e81d7R19 What do you think? 

I no longer have a problem about merging this branch (if you're as well happy with the solution)

**Comment by xuanxu** [comment]
@bertocq yeah, nice way to test the file contents! 
I'm missing a detail: testing that only users with `newsletter == true` are included in the Zip file. Can you change the test to create 2 users, one with `newsletter: false` and another with `newsletter: true` and expect that only the right one is included in the zip file?

**Comment by bertocq** [comment]
@xuanxu you're right! My bad, I was just testing with the admin user that was created. Fixed at https://github.com/consul/consul/pull/1557/commits/4ab92731b6e2f2a6abf31b757e918ed5639c3ba9

**Comment by xuanxu** [comment]
Great! Thank you @bertocq!!

**Pull request merged**
