### PR TITLE
Add settings for control count featured proposals

### PR DESCRIPTION
**Pull request by artofhuman**
What
====
- New setting `count_featured_proposals` allows controlling count featured proposals in yellow block on proposals page. If we don't want this block we can set 0 for example

Deployment
==========
- As before

Warnings
========
- No

### CODE REVIEW

**Comment by decabeza** [comment]
Thanks @artofhuman! 👍 

Some pending details:

- Adds `Setting["count_featured_proposals"]` on `/db/seeds.rb` 
- Adds `Setting.create(key: 'count_featured_proposals', value: '3')` on `db/dev_seeds.rb`

With that this setting can be changed on Admin panel. 

- Also include some specs to test this feature works correctly 😉

**Comment by bertocq** [comment]
@artofhuman sorry for the delay! 🙇  We're tight on time after August holidays... I'm retrying Travis tests build to see if there where some flaky tests

**Comment by artofhuman** [comment]
I think it really fails, but I'm not had time now to check why tests fails, I'll try to fix it in the near future

**Comment by decabeza** [comment]
Hi @artofhuman,

I close this PR because unfortunately this code became obsolete and this functionality was included in a later PR (https://github.com/consul/consul/pull/3081/). Now admins can change the number of featured proposals on settings.

admin:settings

I apologize and thank you for the time and effort dedicated to your contribution.

🙏 😌

**Pull request closed without merging**
